#!/bin/bash

#
# Configuration file for default serial CPU tests
#

#-------------------------------------------------------------------------------
# Branches 
#
branch="master"
regtests_branch="cleanup"

#-------------------------------------------------------------------------------
# Architecture
#
architecture="cpu-serial"

#-------------------------------------------------------------------------------
# CMake args
#
cmake_args+=("-DBUILD_TYPE=Debug")
cmake_args+=("-DPLATFORMS=SERIAL")
cmake_args+=("-DOPALX_ENABLE_UNIT_TESTS=ON")
cmake_args+=("-DOPALX_USE_INSTALLED_HDF5=ON")
cmake_args+=("-DOPALX_USE_INSTALLED_H5HUT=ON")
cmake_args+=("-DOPALX_USE_INSTALLED_GTEST=ON")

#-------------------------------------------------------------------------------
# OPALX args 
#
#opalx_args=()

#-------------------------------------------------------------------------------
# Unit tests args
#
#unittests_args=()
